### ISSUE TITLE
Feature request: lvmd deployed as daemonset

### ISSUE THREAD

**Issue by jmolmo** [alauda/topolvm-operator#71]
This change is suggested by the topolvm project recommendations for  [topolvm production deployments](https://github.com/topolvm/topolvm/blob/main/deploy/README.md#setup-lvmd-using-kubernetes-daemonset).

Currently lvmd is deployed as part of the [node deployment](https://github.com/alauda/topolvm-operator/blob/2e3b0eda6f03badb42d6201cd9e05312576e81bf/pkg/operator/node/node.go#L155).
The node deployment is for each cluster node and takes care that the lvmd config passsed to each lvmd container (using the lvmdconfig configmap) provides the proper values for:
- communication socket: Must be the same used for topolvm-node containers
- Device classes configuration: that can be different for each node depending of the user preferences in the topolvm cluster CRD.

Things to discuss:
1. Possible implementations.
a) Deploy lvmd as daemonset: Requires to pass in someway the different node configuration to the lvmd deployed in each node.... deploy 1 daemonset for node?

b) Change node deployment to daemonset

c) changes in lvmd to pass variable configuration using a command instead a config file.

**Comment by jmolmo** [comment]
I think that probably option b is the best.

**Comment by Muyan0828** [comment]
@jmolmo 
topolvm community deploying node plugin as a DaemonSet.
creating a DaemonSet for lvmd when the same device-classes configuration is used on all nodes.
creating a DaemonSet for lvmd on each node when nodes use different device-classes configuration.

Do we need to adopt the deployment method recommended by the community?
I don’t quite understand the benefits of adopting community deployment

**Comment by travisn** [comment]
@jmolmo What is the need to change to the DaemonSet? If each node requires a unique config, keeping it as a Deployment makes sense. If the nodes are all the same, then a DaemonSet makes sense. Seems like the topolvm project just uses the DaemonSet to easily deploy it on all nodes, but may not be needed for consistency.

**Comment by leelavg** [comment]
@Muyan0828

- I also wanted to get clarified this from @little-guy-lxr on https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971440605
- So, do you also feel the same to have `lvmd` part of `nodeplugin` and have nodeplugin installed as a deployment (the existing way)?

**Comment by Muyan0828** [comment]
> @Muyan0828
> 
> * I also wanted to get clarified this from @little-guy-lxr on [WIP: topolvm lvmd deployed as daemonset #69 (comment)](https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971440605)

He may misunderstand that only one DaemonSet is created for lvmd in cluster

> * So, do you also feel the same to have `lvmd` part of `nodeplugin` and have nodeplugin installed as a deployment (the existing way)?

I just think it is a bit strange to create a DaemonSet for each `lvmd`. 
We can split `lvmd` from `nodeplugin`, but must we create a DaemonSet for it? Maybe deployment is more appropriate?

**Comment by Muyan0828** [comment]
> @Muyan0828
> 
> * I also wanted to get clarified this from @little-guy-lxr on [WIP: topolvm lvmd deployed as daemonset #69 (comment)](https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971440605)
> * So, do you also feel the same to have `lvmd` part of `nodeplugin` and have nodeplugin installed as a deployment (the existing way)?

**Comment by Muyan0828** [comment]
> @Muyan0828
> 
> * I also wanted to get clarified this from @little-guy-lxr on [WIP: topolvm lvmd deployed as daemonset #69 (comment)](https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971440605)
> * So, do you also feel the same to have `lvmd` part of `nodeplugin` and have nodeplugin installed as a deployment (the existing way)?

@little-guy-lxr  may misunderstand that only one DaemonSet is created for lvmd in cluster

I just think it is a bit strange to create a DaemonSet for each lvmd.
We can split lvmd from nodeplugin, but must we create a DaemonSet for it? Maybe deployment is more appropriate?

**Comment by leelavg** [comment]
- We can split lvmd since daemonset isn't appropriate we'll eventually use deployment for lvmd anyways

- However, I believe nodeplugin tightly depends on lvmd there's no point in splitting the both into their own pods and mount configmaps into both of them
- The intention in raising this issue is, original topolvm suggests lvmd to be a daemonset, if we were to follow that we thought of above mentioned three ways but doesn't mean it's not debatable
- We are fine to not to touch existing flow of deploying nodeplugin and lvmd and at the same time, wanted to find any edge cases/failures that may result in deploying this way based on your experience with the operator
- Having said that, CSI community [recommended](https://github.com/kubernetes/community/blob/e5e4d918a177a82f33b6388658d91f62b37bfb4a/contributors/design-proposals/storage/container-storage-interface.md#recommended-mechanism-for-deploying-csi-drivers-on-kubernetes) way of deploying nodeplugin is via a DaemonSet and I feel one of the reasons which isn't documented in the link would be to allow for smoother upgrades draining a node with ignoring daemonset but unfortunately in case of topolvm the PVC is RWO/RWOP which doesn't get benefited from having nodeplugin as daemonset where app pods couldn't be moved to other nodes as well 😓 
- All in all by stating above info, I'm trying to consolidate all possibilities and as stated earlier we are fine to continue with existing deployment model if you can revisit existing usage of operator and didn't find any edge cases doing so, would you also think having a dialogue with Topolvm team to ask for any failure scenarios if nodeplugin and lvmd is installed as a deployment will be helpful?

**Comment by jmolmo** [comment]
> @jmolmo What is the need to change to the DaemonSet? If each node requires a unique config, keeping it as a Deployment makes sense. If the nodes are all the same, then a DaemonSet makes sense. Seems like the topolvm project just uses the DaemonSet to easily deploy it on all nodes, but may not be needed for consistency.

@travisn : I think that @leelavg has explained very well the motivation in his previous [comment]( https://github.com/alauda/topolvm-operator/issues/71#issuecomment-973803643).

**Comment by jmolmo** [comment]
After reading all the comments, and taking into account that lvmd config can be different for each node. I think that probably it has nosense to do any changes in the current implementation.
As @leelavg has pointed, we only need to be sure that the current deployment model works well in any production use case. 

@little-guy-lxr : Do you agree to remove this change from the [list of things](https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971354138) to use "origin-topolvm" as main branch?

**Comment by little-guy-lxr** [comment]
> After reading all the comments, and taking into account that lvmd config can be different for each node. I think that probably it has nosense to do any changes in the current implementation. As @leelavg has pointed, we only need to be sure that the current deployment model works well in any production use case.
> 
> @little-guy-lxr : Do you agree to remove this change from the [list of things](https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971354138) to use "origin-topolvm" as main branch?

@jmolmo  I agree to remove, I add this to the list because we have different opinions on this problem, I could not find some benefits from modifying daemonset to deployment.
