### ISSUE TITLE
feature request: use topolvm scheduler extension  instead of CSIStorageCapacity FG depending of the k8s version 

### ISSUE THREAD

**Issue by jmolmo** [alauda/topolvm-operator#80]
Requested by @little-guy-lxr ([see comment in pr 69](https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971354138))

**Comment by jmolmo** [comment]
@little-guy-lxr : Maybe this FR is something that is not going to be used in the operator.

The operator has used from the very beginning CSIStorageCapacity. The Topolvm project support  k8s versions 1.22, 1.21, 1.20, and CSIStorageCapacity is enabled by default starting with k8s 1.21 , so this FR only will affect to the use of the topolvm-operator with k8s version 1.20.
So this FR, seems to be useful only for a very particular use case, and taking into account that previous installations using topolvm operator already used CSIStorageCapacity, (so the user installed in k8s clusters using v.1.21 or upper)  maybe this is not worth to do this.( What i see is that is not going to be used never.)

Maybe i miss something, can you please clarify if there are other use cases where this feature will be used?

**Comment by little-guy-lxr** [comment]
I think there are two options

1. topolvm-operator just support origin topolvm image that support CSIStorageCapacity. Limit the K8S version to 1.20 or upper

2. topolvm operator support extension scheduler and  CSIStorageCapacity.  This choice results in the need to configure kube-Scheduler, this is cumbersome and error-prone.

It would be a good choice for the TopolVM operator to rely on  CSIStorageCapacity for scheduling.

I commented in pr  https://github.com/alauda/topolvm-operator/pull/69#issuecomment-971354138. because I think you want to support lower version of TopolVM.

**Comment by leelavg** [comment]
@little-guy-lxr

- ack, thanks for the confirmation, we aren't targeting any lower versions that the current operator doesn't support
- the three things proposed by you are either fixed or deferred, do you think of any other reasons that swapping `main` with `origin-topolvm` would result in any issue (like snapshot removal etc)?
- if everything's good, when can we anticipate (just ballpark figure) the branch renames?

**Comment by little-guy-lxr** [comment]
I think the areas of concern have been resolved.

 we should be able to change origin-topolvm to main soon after I change the action wrokflow.

**Comment by little-guy-lxr** [comment]
origin-topolvm branch has renamed to main, please update in local
